# Generated by Django 4.1.7 on 2023-05-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_projet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.projet')),
            ],
        ),
    ]
