# Generated by Django 4.1.7 on 2023-05-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projet'),
        ),
    ]
