# Generated by Django 4.1.7 on 2023-05-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_projet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipe'),
        ),
    ]
