# Generated by Django 4.1.7 on 2023-05-20 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0011_client_projectrequest_client_projects_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
