# Generated by Django 4.1.7 on 2023-05-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_equipe_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
