# Generated by Django 4.1.7 on 2023-05-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_client_gmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fichier_cv', models.FileField(upload_to='cv')),
                ('image', models.ImageField(blank=True, null=True, upload_to='personnel')),
                ('lien_linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
