# Generated by Django 4.1.7 on 2023-05-15 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('acheve', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projet')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CG', 'Charte graphique'), ('O3D', 'Objet 3D'), ('SC', 'Scénarisation')], max_length=3)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='details')),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projet')),
            ],
        ),
    ]
