# Generated by Django 4.1.7 on 2023-05-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='members',
            field=models.ManyToManyField(to='api.personnel'),
        ),
    ]
