# Generated by Django 4.1.7 on 2023-05-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_officialinfo_personalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CG', 'Charte graphique'), ('O3D', 'Objet 3D'), ('SC', 'Scénarisation')], max_length=3)),
                ('description', models.TextField()),
            ],
        ),
    ]
