# Generated by Django 4.1.7 on 2023-05-22 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_equipe_service_demandeprojet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeprojet',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.service'),
        ),
    ]
