# Generated by Django 4.1.7 on 2023-05-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_demandeprojet_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeprojet',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='demandeprojet',
            name='service',
        ),
    ]
