# Generated by Django 4.1.7 on 2023-05-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_formateur_formation_panier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipe',
            new_name='Equipes',
        ),
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
    ]
