# Generated by Django 4.1.7 on 2023-05-22 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_equipe_equipes_rename_service_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.services'),
        ),
    ]
